added the ability to change file name
andypern/vast-scripts pull request #21
Opened 2024-06-08 21:34 UTC by Marounissa

2024-06-09 14:07 UTC, breuner reviewed
hi @Marounissa, generally all good with additing this. only small problem is the indentation change that i mentioned. can you please resubmit without that?

2024-06-09 14:07 UTC, breuner commented on vast-perf.sh
> +        --proxy=*)
the indentation of several lines in the parameter check section got changed unintentionally.

2024-06-10 21:53 UTC, cpeel requested changes

2024-06-10 21:53 UTC, cpeel commented on vast-perf.sh
> +file_name="randrw"
This ends up being the prefix for the filename, but it's actually the fio job name. I'd prefer to see it be called `JOB_NAME` so users aren't surprised when this isn't actually the name of the file that gets created.

2024-06-10 21:53 UTC, cpeel commented on vast-perf.sh
> +        --name=*) file_name="${1#*=}" ;;
`--job-name` would be a better name for this argument, placed near `--jobs` below. It also needs to be added to the usage statement.

2024-06-20 21:47 UTC, cpeel approved these changes
I addressed the PR comments and tested this on selab-var-201.

2024-06-20 21:48 UTC, merged